//
//  MealDBJson.swift
//  Meal Ideas
//
//  Created by Steve Plavetzky on 11/23/21.
//

import Foundation

final class MealDBJSON: Codable{
    static let sample = """
{
  "meals": [
    {
      "idMeal": "52975",
      "strMeal": "Tuna and Egg Briks",
      "strDrinkAlternate": null,
      "strCategory": "Seafood",
      "strArea": "Tunisian",
      "strInstructions": "Heat ",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/2dsltq1560461468.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=C5n1fN8TGHs",
      "strIngredient1": "Olive Oil",
      "strIngredient2": "Spring Onions",
      "strIngredient3": "Spinach",
      "strIngredient4": "Filo Pastry",
      "strIngredient5": "Tuna",
      "strIngredient6": "Eggs",
      "strIngredient7": "Hotsauce",
      "strIngredient8": "Tomatoes",
      "strIngredient9": "Cucumber",
      "strIngredient10": "Lemon Juice",
      "strIngredient11": "Apricot Jam",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "2 tbs",
      "strMeasure2": "8",
      "strMeasure3": "200g",
      "strMeasure4": "4",
      "strMeasure5": "1 can ",
      "strMeasure6": "2",
      "strMeasure7": "Dash",
      "strMeasure8": "4 Chopped",
      "strMeasure9": "1/4 ",
      "strMeasure10": "1 tbs",
      "strMeasure11": "4 tbs",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "http://allrecipes.co.uk/recipe/3096/tunisian-tuna-and-egg-briks.aspx",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52764",
      "strMeal": "Garides Saganaki",
      "strDrinkAlternate": null,
      "strCategory": "Seafood",
      "strArea": "Greek",
      "strInstructions": "Place ",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/wuvryu1468232995.jpg",
      "strTags": "Seafood,Shellfish",
      "strYoutube": "https://www.youtube.com/watch?v=uO0ejc85zSE",
      "strIngredient1": "Raw king prawns",
      "strIngredient2": "Olive oil",
      "strIngredient3": "Chopped onion",
      "strIngredient4": "Freshly chopped parsley",
      "strIngredient5": "White wine",
      "strIngredient6": "Chopped tomatoes",
      "strIngredient7": "Minced garlic",
      "strIngredient8": "Cubed Feta cheese",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": null,
      "strIngredient17": null,
      "strIngredient18": null,
      "strIngredient19": null,
      "strIngredient20": null,
      "strMeasure1": "500g",
      "strMeasure2": "3 tablespoons",
      "strMeasure3": "1",
      "strMeasure4": "pinch",
      "strMeasure5": "250ml",
      "strMeasure6": "1 (400g) tin",
      "strMeasure7": "1/2 teaspoon",
      "strMeasure8": "1 (200g) pack",
      "strMeasure9": "",
      "strMeasure10": "",
      "strMeasure11": "",
      "strMeasure12": "",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": null,
      "strMeasure17": null,
      "strMeasure18": null,
      "strMeasure19": null,
      "strMeasure20": null,
      "strSource": null,
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52796",
      "strMeal": "Chicken Alfredo Primavera",
      "strDrinkAlternate": null,
      "strCategory": "Chicken",
      "strArea": "Italian",
      "strInstructions": "Heat 1 tables",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/syqypv1486981727.jpg",
      "strTags": "Pasta,Meat,Dairy",
      "strYoutube": "https://www.youtube.com/watch?v=qCIbq8HywpQ",
      "strIngredient1": "Butter",
      "strIngredient2": "Olive Oil",
      "strIngredient3": "Chicken",
      "strIngredient4": "Salt",
      "strIngredient5": "Squash",
      "strIngredient6": "Broccoli",
      "strIngredient7": "mushrooms",
      "strIngredient8": "Pepper",
      "strIngredient9": "onion",
      "strIngredient10": "garlic",
      "strIngredient11": "red pepper flakes",
      "strIngredient12": "white wine",
      "strIngredient13": "milk",
      "strIngredient14": "heavy cream",
      "strIngredient15": "Parmesan cheese",
      "strIngredient16": "bowtie pasta",
      "strIngredient17": "Salt",
      "strIngredient18": "Pepper",
      "strIngredient19": "Parsley",
      "strIngredient20": "",
      "strMeasure1": "2 tablespoons",
      "strMeasure2": "3 tablespoons",
      "strMeasure3": "5 boneless",
      "strMeasure4": "1 teaspoon",
      "strMeasure5": "1 cut into 1/2-inch cubes",
      "strMeasure6": "1 Head chopped",
      "strMeasure7": "8-ounce sliced",
      "strMeasure8": "1 red",
      "strMeasure9": "1 chopped",
      "strMeasure10": "3 cloves",
      "strMeasure11": "1/2 teaspoon",
      "strMeasure12": "1/2 cup",
      "strMeasure13": "1/2 cup",
      "strMeasure14": "1/2 cup",
      "strMeasure15": "1 cup grated",
      "strMeasure16": "16 ounces",
      "strMeasure17": "pinch",
      "strMeasure18": "pinch ",
      "strMeasure19": "chopped",
      "strMeasure20": "",
      "strSource": "",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52908",
      "strMeal": "Ratatouille",
      "strDrinkAlternate": null,
      "strCategory": "Vegetarian",
      "strArea": "French",
      "strInstructions": "Cut the aubergines in half l",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/wrpwuu1511786491.jpg",
      "strTags": "Vegetables,SideDish",
      "strYoutube": "https://www.youtube.com/watch?v=BFdQUgAFtGU",
      "strIngredient1": "Aubergine",
      "strIngredient2": "Courgettes",
      "strIngredient3": "Yellow Pepper",
      "strIngredient4": "Tomato",
      "strIngredient5": "Olive Oil",
      "strIngredient6": "Basil",
      "strIngredient7": "Onion",
      "strIngredient8": "Garlic Clove",
      "strIngredient9": "Red Wine Vinegar",
      "strIngredient10": "Sugar",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "2 large",
      "strMeasure2": "4",
      "strMeasure3": "2",
      "strMeasure4": "4 large",
      "strMeasure5": "5 tbs",
      "strMeasure6": "Bunch",
      "strMeasure7": "1 medium",
      "strMeasure8": "3 finely chopped",
      "strMeasure9": "1 tsp ",
      "strMeasure10": "1 tsp ",
      "strMeasure11": "",
      "strMeasure12": "",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "https://www.bbcgoodfood.com/recipes/2903/ratatouille",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52915",
      "strMeal": "French Omelette",
      "strDrinkAlternate": null,
      "strCategory": "Miscellaneous",
      "strArea": "French",
      "strInstructions": "Get everything re.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/yvpuuy1511797244.jpg",
      "strTags": "Egg",
      "strYoutube": "https://www.youtube.com/watch?v=qXPhVYpQLPA",
      "strIngredient1": "Eggs",
      "strIngredient2": "Butter",
      "strIngredient3": "Parmesan",
      "strIngredient4": "Tarragon",
      "strIngredient5": "Parsley",
      "strIngredient6": "Chives",
      "strIngredient7": "Gruyère",
      "strIngredient8": "",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "3",
      "strMeasure2": "2 knobs",
      "strMeasure3": "1 tsp ",
      "strMeasure4": "3 chopped",
      "strMeasure5": "1 tbs chopped",
      "strMeasure6": "1 tbs chopped",
      "strMeasure7": "4 tbs",
      "strMeasure8": "",
      "strMeasure9": "",
      "strMeasure10": "",
      "strMeasure11": "",
      "strMeasure12": "",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "https://www.bbcgoodfood.com/recipes/1669/ultimate-french-omelette",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52967",
      "strMeal": "Home-made Mandazi",
      "strDrinkAlternate": null,
      "strCategory": "Breakfast",
      "strArea": "Kenyan",
      "strInstructions": "This is one recipe a lot of people",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/thazgm1555350962.jpg",
      "strTags": "Baking,Breakfast,Egg,Warm,Snack",
      "strYoutube": "",
      "strIngredient1": "Self-raising Flour",
      "strIngredient2": "Sugar",
      "strIngredient3": "Eggs",
      "strIngredient4": "Milk",
      "strIngredient5": "",
      "strIngredient6": "",
      "strIngredient7": "",
      "strIngredient8": "",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "750g",
      "strMeasure2": "6 tablespoons",
      "strMeasure3": "2",
      "strMeasure4": "1 cup ",
      "strMeasure5": " ",
      "strMeasure6": " ",
      "strMeasure7": " ",
      "strMeasure8": " ",
      "strMeasure9": " ",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "http://chef-raphael.com/home-made-mandazi-recipe/#more-106",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52839",
      "strMeal": "Chilli prawn linguine",
      "strDrinkAlternate": null,
      "strCategory": "Pasta",
      "strArea": "Italian",
      "strInstructions": "Mix the dressing in",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/usywpp1511189717.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=SC17Mc70Db0",
      "strIngredient1": "Linguine Pasta",
      "strIngredient2": "Sugar Snap Peas",
      "strIngredient3": "Olive Oil",
      "strIngredient4": "Garlic Clove",
      "strIngredient5": "Red Chilli",
      "strIngredient6": "King Prawns",
      "strIngredient7": "Cherry Tomatoes",
      "strIngredient8": "Basil Leaves",
      "strIngredient9": "Lettuce",
      "strIngredient10": "Bread",
      "strIngredient11": "Fromage Frais",
      "strIngredient12": "Lime",
      "strIngredient13": "Caster Sugar",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "280g",
      "strMeasure2": "200g",
      "strMeasure3": "2 tblsp ",
      "strMeasure4": "2 cloves chopped",
      "strMeasure5": "1 large",
      "strMeasure6": "24 Skinned",
      "strMeasure7": "12",
      "strMeasure8": "Handful",
      "strMeasure9": "Leaves",
      "strMeasure10": "to serve",
      "strMeasure11": "2 tbsp",
      "strMeasure12": "Grated Zest of 2",
      "strMeasure13": "2 tsp",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "https://www.bbcgoodfood.com/recipes/1269/chilli-prawn-linguine",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52814",
      "strMeal": "Thai Green Curry",
      "strDrinkAlternate": null,
      "strCategory": "Chicken",
      "strArea": "Thai",
      "strInstructions": "Put the potatoes in a pan of boiling water and cook for 5 minutes. Throw in the beans and cook for a further 3 m",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/sstssx1487349585.jpg",
      "strTags": "Curry,Mild",
      "strYoutube": "https://www.youtube.com/watch?v=LIbKVpBQKJI",
      "strIngredient1": "potatoes",
      "strIngredient2": "green beans",
      "strIngredient3": "sunflower oil",
      "strIngredient4": "garlic",
      "strIngredient5": "Thai green curry paste",
      "strIngredient6": "coconut milk",
      "strIngredient7": "Thai fish sauce",
      "strIngredient8": "Sugar",
      "strIngredient9": "Chicken",
      "strIngredient10": "lime",
      "strIngredient11": "basil",
      "strIngredient12": "Rice",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "225g new",
      "strMeasure2": "100g ",
      "strMeasure3": "1 tbsp",
      "strMeasure4": "1 clove",
      "strMeasure5": "4 tsp ",
      "strMeasure6": "400ml",
      "strMeasure7": "2 tsp",
      "strMeasure8": "1 tsp",
      "strMeasure9": "450g boneless",
      "strMeasure10": "2 fresh kaffir leaves",
      "strMeasure11": "handfull",
      "strMeasure12": "Boiled",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "http://www.bbcgoodfood.com/recipes/3235/thai-green-chicken-curry",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "53013",
      "strMeal": "Big Mac",
      "strDrinkAlternate": null,
      "strCategory": "Beef",
      "strArea": "American",
      "strInstructions": "For the Big Ma",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/urzj1d1587670726.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=C5J39YnnPsg",
      "strIngredient1": "Minced Beef",
      "strIngredient2": "Olive Oil",
      "strIngredient3": "Sesame Seed Burger Buns",
      "strIngredient4": "Onion",
      "strIngredient5": "Iceberg Lettuce",
      "strIngredient6": "Cheese",
      "strIngredient7": "Dill Pickles",
      "strIngredient8": "Mayonnaise",
      "strIngredient9": "White Wine Vinegar",
      "strIngredient10": "Pepper",
      "strIngredient11": "Mustard",
      "strIngredient12": "Onion Salt",
      "strIngredient13": "Garlic Powder",
      "strIngredient14": "Paprika",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "400g",
      "strMeasure2": "2 tbs",
      "strMeasure3": "2",
      "strMeasure4": "Chopped",
      "strMeasure5": "1/4 ",
      "strMeasure6": "2 sliced",
      "strMeasure7": "2 large",
      "strMeasure8": "1 cup ",
      "strMeasure9": "2 tsp",
      "strMeasure10": "Pinch",
      "strMeasure11": "2 tsp",
      "strMeasure12": "1 1/2 tsp ",
      "strMeasure13": "1 1/2 tsp ",
      "strMeasure14": "1/2 tsp",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.delicious.com.au/recipes/finally-recipe-worlds-top-selling-burger-big-mac/5221ee4a-279e-4a0b-8629-f442dc46822e",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52945",
      "strMeal": "Kung Pao Chicken",
      "strDrinkAlternate": null,
      "strCategory": "Chicken",
      "strArea": "Chinese",
      "strInstructions": "Combine the sake or ",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/1525872624.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=QqdcCHQlOe0",
      "strIngredient1": "Sake",
      "strIngredient2": "Soy Sauce",
      "strIngredient3": "Sesame Seed Oil",
      "strIngredient4": "Corn Flour",
      "strIngredient5": "Water",
      "strIngredient6": "Chicken",
      "strIngredient7": "Chilli Powder",
      "strIngredient8": "Rice Vinegar",
      "strIngredient9": "Brown Sugar",
      "strIngredient10": "Spring Onions",
      "strIngredient11": "Garlic Clove",
      "strIngredient12": "Water Chestnut",
      "strIngredient13": "Peanuts",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "2 tbs",
      "strMeasure2": "2 tbs",
      "strMeasure3": "2 tbs",
      "strMeasure4": "2 tbs",
      "strMeasure5": "2 tbs",
      "strMeasure6": "500g",
      "strMeasure7": "1 tbs",
      "strMeasure8": "1 tsp ",
      "strMeasure9": "1 tbs",
      "strMeasure10": "4 Chopped",
      "strMeasure11": "6 cloves",
      "strMeasure12": "220g",
      "strMeasure13": "100g ",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "http://allrecipes.co.uk/recipe/1773/kung-pao-chicken.aspx",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    }
  ]
}
"""
}


//Original:
/*
final class MealDBJSON: Codable{
    static let sample = """
{
  "meals": [
    {
      "idMeal": "52975",
      "strMeal": "Tuna and Egg Briks",
      "strDrinkAlternate": null,
      "strCategory": "Seafood",
      "strArea": "Tunisian",
      "strInstructions": "Heat 2 tsp of the oil in a large saucepan and cook the spring onions over a low heat for 3 minutes or until beginning to soften. Add the spinach, cover with a tight-fitting lid and cook for a further 2–3 minutes or until tender and wilted, stirring once or twice. Tip the mixture into a sieve or colander and leave to drain and cool.\r\nUsing a saucer as a guide, cut out 24 rounds about 12.5 cm (5 in) in diameter from the filo pastry, cutting 6 rounds from each sheet. Stack the filo rounds in a pile, then cover with cling film to prevent them from drying out.\r\nWhen the spinach mixture is cool, squeeze out as much excess liquid as possible, then transfer to a bowl. Add the tuna, eggs, hot pepper sauce, and salt and pepper to taste. Mix well.\r\nPreheat the oven to 200°C (400°F, gas mark 6). Take one filo round and very lightly brush with some of the remaining oil. Top with a second round and brush with a little oil, then place a third round on top and brush with oil.\r\nPlace a heaped tbsp of the filling in the middle of the round, then fold the pastry over to make a half-moon shape. Fold in the edges, twisting them to seal, and place on a non-stick baking sheet. Repeat with the remaining pastry and filling to make 8 briks in all.\r\nLightly brush the briks with the remaining oil. Bake for 12–15 minutes or until the pastry is crisp and golden brown.\r\nMeanwhile, combine the tomatoes and cucumber in a bowl and sprinkle with the lemon juice and seasoning to taste. Serve the briks hot with this salad and the chutney.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/2dsltq1560461468.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=C5n1fN8TGHs",
      "strIngredient1": "Olive Oil",
      "strIngredient2": "Spring Onions",
      "strIngredient3": "Spinach",
      "strIngredient4": "Filo Pastry",
      "strIngredient5": "Tuna",
      "strIngredient6": "Eggs",
      "strIngredient7": "Hotsauce",
      "strIngredient8": "Tomatoes",
      "strIngredient9": "Cucumber",
      "strIngredient10": "Lemon Juice",
      "strIngredient11": "Apricot Jam",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "2 tbs",
      "strMeasure2": "8",
      "strMeasure3": "200g",
      "strMeasure4": "4",
      "strMeasure5": "1 can ",
      "strMeasure6": "2",
      "strMeasure7": "Dash",
      "strMeasure8": "4 Chopped",
      "strMeasure9": "1/4 ",
      "strMeasure10": "1 tbs",
      "strMeasure11": "4 tbs",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "http://allrecipes.co.uk/recipe/3096/tunisian-tuna-and-egg-briks.aspx",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52764",
      "strMeal": "Garides Saganaki",
      "strDrinkAlternate": null,
      "strCategory": "Seafood",
      "strArea": "Greek",
      "strInstructions": "Place the prawns in a pot and add enough water to cover. Boil for 5 minutes. Drain, reserving the liquid, and set aside.\r\nHeat 2 tablespoons of oil in a saucepan. Add the onion; cook and stir until soft. Mix in the parsley, wine, tomatoes, garlic and remaining olive oil. Simmer, stirring occasionally, for about 30 minutes, or until the sauce is thickened.\r\nWhile the sauce is simmering, the prawns should become cool enough to handle. First remove the legs by pinching them, and then pull off the shells, leaving the head and tail on.\r\nWhen the sauce has thickened, stir in the prawns. Bring to a simmer again if the sauce has cooled with the prawns, and cook for about 5 minutes. Add the feta and remove from the heat. Let stand until the cheese starts to melt. Serve warm with slices of crusty bread.\r\nThough completely untraditional, you can add a few tablespoons of stock or passata to this recipe to make a delicious pasta sauce. Toss with pasta after adding the feta, and serve.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/wuvryu1468232995.jpg",
      "strTags": "Seafood,Shellfish",
      "strYoutube": "https://www.youtube.com/watch?v=uO0ejc85zSE",
      "strIngredient1": "Raw king prawns",
      "strIngredient2": "Olive oil",
      "strIngredient3": "Chopped onion",
      "strIngredient4": "Freshly chopped parsley",
      "strIngredient5": "White wine",
      "strIngredient6": "Chopped tomatoes",
      "strIngredient7": "Minced garlic",
      "strIngredient8": "Cubed Feta cheese",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": null,
      "strIngredient17": null,
      "strIngredient18": null,
      "strIngredient19": null,
      "strIngredient20": null,
      "strMeasure1": "500g",
      "strMeasure2": "3 tablespoons",
      "strMeasure3": "1",
      "strMeasure4": "pinch",
      "strMeasure5": "250ml",
      "strMeasure6": "1 (400g) tin",
      "strMeasure7": "1/2 teaspoon",
      "strMeasure8": "1 (200g) pack",
      "strMeasure9": "",
      "strMeasure10": "",
      "strMeasure11": "",
      "strMeasure12": "",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": null,
      "strMeasure17": null,
      "strMeasure18": null,
      "strMeasure19": null,
      "strMeasure20": null,
      "strSource": null,
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52796",
      "strMeal": "Chicken Alfredo Primavera",
      "strDrinkAlternate": null,
      "strCategory": "Chicken",
      "strArea": "Italian",
      "strInstructions": "Heat 1 tablespoon of butter and 2 tablespoons of olive oil in a large skillet over medium-high heat. Season both sides of each chicken breast with seasoned salt and a pinch of pepper. Add the chicken to the skillet and cook for 5-7 minutes on each side, or until cooked through.  While the chicken is cooking, bring a large pot of water to a boil. Season the boiling water with a few generous pinches of kosher salt. Add the pasta and give it a stir. Cook, stirring occasionally, until al dente, about 12 minutes. Reserve 1/2 cup of  pasta water before draining the pasta.  Remove the chicken from the pan and transfer it to a cutting board; allow it to rest. Turn the heat down to medium and dd the remaining 1 tablespoon of butter and olive oil to the same pan you used to cook the chicken. Add the veggies (minus the garlic) and red pepper flakes to the pan and stir to coat with the oil and butter (refrain from seasoning with salt until the veggies are finished browning). Cook, stirring often, until the veggies are tender, about 5 minutes. Add the garlic and a generous pinch of salt and pepper to the pan and cook for 1 minute.  Deglaze the pan with the white wine. Continue to cook until the wine has reduced by half, about 3 minutes. Stir in the milk, heavy cream, and reserved pasta water. Bring the mixture to a gentle boil and allow to simmer and reduce for 2-3 minutes. Turn off the heat and add the Parmesan cheese and cooked pasta. Season with salt and pepper to taste. Garnish with Parmesan cheese and chopped parsley, if desired. ",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/syqypv1486981727.jpg",
      "strTags": "Pasta,Meat,Dairy",
      "strYoutube": "https://www.youtube.com/watch?v=qCIbq8HywpQ",
      "strIngredient1": "Butter",
      "strIngredient2": "Olive Oil",
      "strIngredient3": "Chicken",
      "strIngredient4": "Salt",
      "strIngredient5": "Squash",
      "strIngredient6": "Broccoli",
      "strIngredient7": "mushrooms",
      "strIngredient8": "Pepper",
      "strIngredient9": "onion",
      "strIngredient10": "garlic",
      "strIngredient11": "red pepper flakes",
      "strIngredient12": "white wine",
      "strIngredient13": "milk",
      "strIngredient14": "heavy cream",
      "strIngredient15": "Parmesan cheese",
      "strIngredient16": "bowtie pasta",
      "strIngredient17": "Salt",
      "strIngredient18": "Pepper",
      "strIngredient19": "Parsley",
      "strIngredient20": "",
      "strMeasure1": "2 tablespoons",
      "strMeasure2": "3 tablespoons",
      "strMeasure3": "5 boneless",
      "strMeasure4": "1 teaspoon",
      "strMeasure5": "1 cut into 1/2-inch cubes",
      "strMeasure6": "1 Head chopped",
      "strMeasure7": "8-ounce sliced",
      "strMeasure8": "1 red",
      "strMeasure9": "1 chopped",
      "strMeasure10": "3 cloves",
      "strMeasure11": "1/2 teaspoon",
      "strMeasure12": "1/2 cup",
      "strMeasure13": "1/2 cup",
      "strMeasure14": "1/2 cup",
      "strMeasure15": "1 cup grated",
      "strMeasure16": "16 ounces",
      "strMeasure17": "pinch",
      "strMeasure18": "pinch ",
      "strMeasure19": "chopped",
      "strMeasure20": "",
      "strSource": "",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52908",
      "strMeal": "Ratatouille",
      "strDrinkAlternate": null,
      "strCategory": "Vegetarian",
      "strArea": "French",
      "strInstructions": "Cut the aubergines in half lengthways. Place them on the board, cut side down, slice in half lengthways again and then across into 1.5cm chunks. Cut off the courgettes ends, then across into 1.5cm slices. Peel the peppers from stalk to bottom. Hold upright, cut around the stalk, then cut into 3 pieces. Cut away any membrane, then chop into bite-size chunks.\r\nScore a small cross on the base of each tomato, then put them into a heatproof bowl. Pour boiling water over the tomatoes, leave for 20 secs, then remove. Pour the water away, replace the tomatoes and cover with cold water. Leave to cool, then peel the skin away. Quarter the tomatoes, scrape away the seeds with a spoon, then roughly chop the flesh.\r\nSet a sauté pan over medium heat and when hot, pour in 2 tbsp olive oil. Brown the aubergines for 5 mins on each side until the pieces are soft. Set them aside and fry the courgettes in another tbsp oil for 5 mins, until golden on both sides. Repeat with the peppers. Don’t overcook the vegetables at this stage, as they have some more cooking left in the next step.\r\nTear up the basil leaves and set aside. Cook the onion in the pan for 5 mins. Add the garlic and fry for a further min. Stir in the vinegar and sugar, then tip in the tomatoes and half the basil. Return the vegetables to the pan with some salt and pepper and cook for 5 mins. Serve with basil.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/wrpwuu1511786491.jpg",
      "strTags": "Vegetables,SideDish",
      "strYoutube": "https://www.youtube.com/watch?v=BFdQUgAFtGU",
      "strIngredient1": "Aubergine",
      "strIngredient2": "Courgettes",
      "strIngredient3": "Yellow Pepper",
      "strIngredient4": "Tomato",
      "strIngredient5": "Olive Oil",
      "strIngredient6": "Basil",
      "strIngredient7": "Onion",
      "strIngredient8": "Garlic Clove",
      "strIngredient9": "Red Wine Vinegar",
      "strIngredient10": "Sugar",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "2 large",
      "strMeasure2": "4",
      "strMeasure3": "2",
      "strMeasure4": "4 large",
      "strMeasure5": "5 tbs",
      "strMeasure6": "Bunch",
      "strMeasure7": "1 medium",
      "strMeasure8": "3 finely chopped",
      "strMeasure9": "1 tsp ",
      "strMeasure10": "1 tsp ",
      "strMeasure11": "",
      "strMeasure12": "",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "https://www.bbcgoodfood.com/recipes/2903/ratatouille",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52915",
      "strMeal": "French Omelette",
      "strDrinkAlternate": null,
      "strCategory": "Miscellaneous",
      "strArea": "French",
      "strInstructions": "Get everything ready. Warm a 20cm (measured across the top) non-stick frying pan on a medium heat. Crack the eggs into a bowl and beat them with a fork so they break up and mix, but not as completely as you would for scrambled egg. With the heat on medium-hot, drop one knob of butter into the pan. It should bubble and sizzle, but not brown. Season the eggs with the Parmesan and a little salt and pepper, and pour into the pan.\r\nLet the eggs bubble slightly for a couple of seconds, then take a wooden fork or spatula and gently draw the mixture in from the sides of the pan a few times, so it gathers in folds in the centre. Leave for a few seconds, then stir again to lightly combine uncooked egg with cooked. Leave briefly again, and when partly cooked, stir a bit faster, stopping while there’s some barely cooked egg left. With the pan flat on the heat, shake it back and forth a few times to settle the mixture. It should slide easily in the pan and look soft and moist on top. A quick burst of heat will brown the underside.\r\nGrip the handle underneath. Tilt the pan down away from you and let the omelette fall to the edge. Fold the side nearest to you over by a third with your fork, and keep it rolling over, so the omelette tips onto a plate – or fold it in half, if that’s easier. For a neat finish, cover the omelette with a piece of kitchen paper and plump it up a bit with your fingers. Rub the other knob of butter over to glaze. Serve immediately.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/yvpuuy1511797244.jpg",
      "strTags": "Egg",
      "strYoutube": "https://www.youtube.com/watch?v=qXPhVYpQLPA",
      "strIngredient1": "Eggs",
      "strIngredient2": "Butter",
      "strIngredient3": "Parmesan",
      "strIngredient4": "Tarragon",
      "strIngredient5": "Parsley",
      "strIngredient6": "Chives",
      "strIngredient7": "Gruyère",
      "strIngredient8": "",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "3",
      "strMeasure2": "2 knobs",
      "strMeasure3": "1 tsp ",
      "strMeasure4": "3 chopped",
      "strMeasure5": "1 tbs chopped",
      "strMeasure6": "1 tbs chopped",
      "strMeasure7": "4 tbs",
      "strMeasure8": "",
      "strMeasure9": "",
      "strMeasure10": "",
      "strMeasure11": "",
      "strMeasure12": "",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "https://www.bbcgoodfood.com/recipes/1669/ultimate-french-omelette",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52967",
      "strMeal": "Home-made Mandazi",
      "strDrinkAlternate": null,
      "strCategory": "Breakfast",
      "strArea": "Kenyan",
      "strInstructions": "This is one recipe a lot of people have requested and I have tried to make it as simple as possible and I hope it will work for you. Make sure you use the right flour which is basically one with raising agents. Adjust the amount of sugar to your taste and try using different flavours to have variety whenever you have them.\r\nYou can use Coconut milk instead of regular milk, you can also add desiccated coconut to the dry flour or other spices like powdered cloves or cinnamon.\r\nFor “healthy looking” mandazis do not roll the dough too thin before frying and use the procedure I have indicated above.\r\n\r\n1. Mix the flour,cinnamon and sugar in a suitable bowl.\r\n2. In a separate bowl whisk the egg into the milk\r\n3. Make a well at the centre of the flour and add the milk and egg mixture and slowly mix to form a dough.\r\n4. Knead the dough for 3-4 minutes or until it stops sticking to the sides of the bowl and you have a smooth surface.\r\n5. Cover the dough with a damp cloth  and allow to rest for 15 minutes.\r\n6. Roll the dough on a lightly floured surface into a 1cm thick piece.\r\n7. Using a sharp small knife, cut the dough into the desired size setting aside ready for deep frying.\r\n8. Heat your oil in a suitable pot and gently dip the mandazi pieces to cook until light brown on the first side then turn to cook on the second side.\r\n9. Serve them warm or cold",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/thazgm1555350962.jpg",
      "strTags": "Baking,Breakfast,Egg,Warm,Snack",
      "strYoutube": "",
      "strIngredient1": "Self-raising Flour",
      "strIngredient2": "Sugar",
      "strIngredient3": "Eggs",
      "strIngredient4": "Milk",
      "strIngredient5": "",
      "strIngredient6": "",
      "strIngredient7": "",
      "strIngredient8": "",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "750g",
      "strMeasure2": "6 tablespoons",
      "strMeasure3": "2",
      "strMeasure4": "1 cup ",
      "strMeasure5": " ",
      "strMeasure6": " ",
      "strMeasure7": " ",
      "strMeasure8": " ",
      "strMeasure9": " ",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "http://chef-raphael.com/home-made-mandazi-recipe/#more-106",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52839",
      "strMeal": "Chilli prawn linguine",
      "strDrinkAlternate": null,
      "strCategory": "Pasta",
      "strArea": "Italian",
      "strInstructions": "Mix the dressing ingredients in a small bowl and season with salt and pepper. Set aside.\r\n\r\nCook the pasta according to the packet instructions. Add the sugar snap peas for the last minute or so of cooking time.\r\n\r\nMeanwhile, heat the oil in a wok or large frying pan, toss in the garlic and chilli and cook over a fairly gentle heat for about 30 seconds without letting the garlic brown. Tip in the prawns and cook over a high heat, stirring frequently, for about 3 minutes until they turn pink.\r\n\r\nAdd the tomatoes and cook, stirring occasionally, for 3 minutes until they just start to soften. Drain the pasta and sugar snaps well, then toss into the prawn mixture. Tear in the basil leaves, stir, and season with salt and pepper.\r\n\r\nServe with salad leaves drizzled with the lime dressing, and warm crusty bread.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/usywpp1511189717.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=SC17Mc70Db0",
      "strIngredient1": "Linguine Pasta",
      "strIngredient2": "Sugar Snap Peas",
      "strIngredient3": "Olive Oil",
      "strIngredient4": "Garlic Clove",
      "strIngredient5": "Red Chilli",
      "strIngredient6": "King Prawns",
      "strIngredient7": "Cherry Tomatoes",
      "strIngredient8": "Basil Leaves",
      "strIngredient9": "Lettuce",
      "strIngredient10": "Bread",
      "strIngredient11": "Fromage Frais",
      "strIngredient12": "Lime",
      "strIngredient13": "Caster Sugar",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "280g",
      "strMeasure2": "200g",
      "strMeasure3": "2 tblsp ",
      "strMeasure4": "2 cloves chopped",
      "strMeasure5": "1 large",
      "strMeasure6": "24 Skinned",
      "strMeasure7": "12",
      "strMeasure8": "Handful",
      "strMeasure9": "Leaves",
      "strMeasure10": "to serve",
      "strMeasure11": "2 tbsp",
      "strMeasure12": "Grated Zest of 2",
      "strMeasure13": "2 tsp",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "https://www.bbcgoodfood.com/recipes/1269/chilli-prawn-linguine",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52814",
      "strMeal": "Thai Green Curry",
      "strDrinkAlternate": null,
      "strCategory": "Chicken",
      "strArea": "Thai",
      "strInstructions": "Put the potatoes in a pan of boiling water and cook for 5 minutes. Throw in the beans and cook for a further 3 minutes, by which time both should be just tender but not too soft. Drain and put to one side.\r\nIn a wok or large frying pan, heat the oil until very hot, then drop in the garlic and cook until golden, this should take only a few seconds. Don’t let it go very dark or it will spoil the taste. Spoon in the curry paste and stir it around for a few seconds to begin to cook the spices and release all the flavours. Next, pour in the coconut milk and let it come to a bubble.\r\nStir in the fish sauce and sugar, then the pieces of chicken. Turn the heat down to a simmer and cook, covered, for about 8 minutes until the chicken is cooked.\r\nTip in the potatoes and beans and let them warm through in the hot coconut milk, then add a lovely citrussy flavour by stirring in the shredded lime leaves (or lime zest). The basil leaves go in next, but only leave them briefly on the heat or they will quickly lose their brightness. Scatter with the lime garnish and serve immediately with boiled rice.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/sstssx1487349585.jpg",
      "strTags": "Curry,Mild",
      "strYoutube": "https://www.youtube.com/watch?v=LIbKVpBQKJI",
      "strIngredient1": "potatoes",
      "strIngredient2": "green beans",
      "strIngredient3": "sunflower oil",
      "strIngredient4": "garlic",
      "strIngredient5": "Thai green curry paste",
      "strIngredient6": "coconut milk",
      "strIngredient7": "Thai fish sauce",
      "strIngredient8": "Sugar",
      "strIngredient9": "Chicken",
      "strIngredient10": "lime",
      "strIngredient11": "basil",
      "strIngredient12": "Rice",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "225g new",
      "strMeasure2": "100g ",
      "strMeasure3": "1 tbsp",
      "strMeasure4": "1 clove",
      "strMeasure5": "4 tsp ",
      "strMeasure6": "400ml",
      "strMeasure7": "2 tsp",
      "strMeasure8": "1 tsp",
      "strMeasure9": "450g boneless",
      "strMeasure10": "2 fresh kaffir leaves",
      "strMeasure11": "handfull",
      "strMeasure12": "Boiled",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "http://www.bbcgoodfood.com/recipes/3235/thai-green-chicken-curry",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "53013",
      "strMeal": "Big Mac",
      "strDrinkAlternate": null,
      "strCategory": "Beef",
      "strArea": "American",
      "strInstructions": "For the Big Mac sauce, combine all the ingredients in a bowl, season with salt and chill until ready to use.\r\n2. To make the patties, season the mince with salt and pepper and form into 4 balls using about 1/3 cup mince each. Place each onto a square of baking paper and flatten to form into four x 15cm circles. Heat oil in a large frypan over high heat. In 2 batches, cook beef patties for 1-2 minutes each side until lightly charred and cooked through. Remove from heat and keep warm. Repeat with remaining two patties.\r\n3. Carefully slice each burger bun into three acrossways, then lightly toast.\r\n4. To assemble the burgers, spread a little Big Mac sauce over the bottom base. Top with some chopped onion, shredded lettuce, slice of cheese, beef patty and some pickle slices. Top with the middle bun layer, and spread with more Big Mac sauce, onion, lettuce, pickles, beef patty and then finish with more sauce. Top with burger lid to serve.\r\n5. After waiting half an hour for your food to settle, go for a jog.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/urzj1d1587670726.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=C5J39YnnPsg",
      "strIngredient1": "Minced Beef",
      "strIngredient2": "Olive Oil",
      "strIngredient3": "Sesame Seed Burger Buns",
      "strIngredient4": "Onion",
      "strIngredient5": "Iceberg Lettuce",
      "strIngredient6": "Cheese",
      "strIngredient7": "Dill Pickles",
      "strIngredient8": "Mayonnaise",
      "strIngredient9": "White Wine Vinegar",
      "strIngredient10": "Pepper",
      "strIngredient11": "Mustard",
      "strIngredient12": "Onion Salt",
      "strIngredient13": "Garlic Powder",
      "strIngredient14": "Paprika",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "400g",
      "strMeasure2": "2 tbs",
      "strMeasure3": "2",
      "strMeasure4": "Chopped",
      "strMeasure5": "1/4 ",
      "strMeasure6": "2 sliced",
      "strMeasure7": "2 large",
      "strMeasure8": "1 cup ",
      "strMeasure9": "2 tsp",
      "strMeasure10": "Pinch",
      "strMeasure11": "2 tsp",
      "strMeasure12": "1 1/2 tsp ",
      "strMeasure13": "1 1/2 tsp ",
      "strMeasure14": "1/2 tsp",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.delicious.com.au/recipes/finally-recipe-worlds-top-selling-burger-big-mac/5221ee4a-279e-4a0b-8629-f442dc46822e",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52945",
      "strMeal": "Kung Pao Chicken",
      "strDrinkAlternate": null,
      "strCategory": "Chicken",
      "strArea": "Chinese",
      "strInstructions": "Combine the sake or rice wine, soy sauce, sesame oil and cornflour dissolved in water. Divide mixture in half.\r\nIn a glass dish or bowl, combine half of the sake mixture with the chicken pieces and toss to coat. Cover dish and place in refrigerator for about 30 minutes.\r\nIn a medium frying pan, combine remaining sake mixture, chillies, vinegar and sugar. Mix together and add spring onion, garlic, water chestnuts and peanuts. Heat sauce slowly over medium heat until aromatic.\r\nMeanwhile, remove chicken from marinade and sauté in a large frying pan until juices run clear. When sauce is aromatic, add sautéed chicken and let simmer together until sauce thickens.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/1525872624.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=QqdcCHQlOe0",
      "strIngredient1": "Sake",
      "strIngredient2": "Soy Sauce",
      "strIngredient3": "Sesame Seed Oil",
      "strIngredient4": "Corn Flour",
      "strIngredient5": "Water",
      "strIngredient6": "Chicken",
      "strIngredient7": "Chilli Powder",
      "strIngredient8": "Rice Vinegar",
      "strIngredient9": "Brown Sugar",
      "strIngredient10": "Spring Onions",
      "strIngredient11": "Garlic Clove",
      "strIngredient12": "Water Chestnut",
      "strIngredient13": "Peanuts",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "2 tbs",
      "strMeasure2": "2 tbs",
      "strMeasure3": "2 tbs",
      "strMeasure4": "2 tbs",
      "strMeasure5": "2 tbs",
      "strMeasure6": "500g",
      "strMeasure7": "1 tbs",
      "strMeasure8": "1 tsp ",
      "strMeasure9": "1 tbs",
      "strMeasure10": "4 Chopped",
      "strMeasure11": "6 cloves",
      "strMeasure12": "220g",
      "strMeasure13": "100g ",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "http://allrecipes.co.uk/recipe/1773/kung-pao-chicken.aspx",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    }
  ]
}
"""
}
*/
